#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: publication
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

* Test category                                                 :test_category:

Test category content.

** Test post one
   :PROPERTIES:
   :EXPORT_FILE_NAME: testpost_publication
   :EXPORT_DATE: 2019-02-02
   :EXPORT_HUGO_MENU: :menu "main"
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :foo bar
   :END:

*** Heading one

Content under heading one.

Para 2 under heading one.

Para 3 under heading one.

Para 4 under heading one.

Para 5 under heading one.

Para 6 under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.

Para under heading one.


